### ISSUE TITLE
Unable to find type [DRSRule.VMGroup]

### ISSUE THREAD

**Issue by cc4in** [PowerCLIGoodies/DRSRule#17] opened 2018-09-05 07:46 UTC
Version: Get-DRSRule 1.2.1

When trying to use a function, always get Errors:

```
Get-DrsVmGroup
Unable to find type [DRSRule.VMGroup].
At C:\Users\XXX\Documents\WindowsPowerShell\Modules\DRSRule\DRSRule.psm1:55 char:15
+   [OutputType([DRSRule.VMGroup],[VMware.Vim.ClusterVmGroup])]
+               ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DRSRule.VMGroup:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Get-DrsVMHostRule
Unable to find type [DRSRule.VMHostGroup].
At C:\Users\XXX\Documents\WindowsPowerShell\Modules\DRSRule\DRSRule.psm1:167 char:15
+   [OutputType([DRSRule.VMHostGroup],[VMware.Vim.ClusterHostGroup])]
+               ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DRSRule.VMHostGroup:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Get-DrsVmHostGroup
Unable to find type [DRSRule.VMHostGroup].
At C:\Users\XXX\Documents\WindowsPowerShell\Modules\DRSRule\DRSRule.psm1:167 char:15
+   [OutputType([DRSRule.VMHostGroup],[VMware.Vim.ClusterHostGroup])]
+               ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DRSRule.VMHostGroup:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

See also:  https://communities.vmware.com/thread/508831
Latest Entrys have the same problem and it seems to be a new Issue.

```

**Comment by mtboren** [comment] 2018-09-16 22:27
Greetings, @cc4in -

Mhmm.  In trying to recreate this issue with the module loaded normally, I failed.  But, we do see this behavior when the module is only partially loaded.

What is the command line that you are using to import the DRSRule module?  Is it like one of the following:
- `Import-Module c:\myModulesDir\DRSRule\DRSRule.psm1`, or
- `Import-Module DRSRule`

?  Let's discuss so that we can get to the bottom of this.  Cheers

**Comment by kungfoochef** [comment] 2018-10-01 14:43
@mtboren 
Similar issue here.  Initially "Import-Module DRSRule" would not error, but any Get-DRS* function would fail with the errors shown above.  Completely removed DRSRule & PowerCLI and started over, installing under my user's scope.  Now results:

> Add-Type : (0) : Metadata file
> ...\Documents\WindowsPowerShell\Modules\VMware.VimAutomation.Core\10.1.0.8344055\net45\VMware.Vim.dll'
> could not be found

I had noticed prior to the module re-install, as I had tried running the init directly to see if any errors were thrown.  The only VMware.Vim.dll I could find is located under ...\Documents\WindowsPowerShell\Modules\VMware.Vim\6.7.0.9288211\net45

I tried hard coding that path in the DRSRule.init file, but that blew up and I don't know enough module coding to decipher what was failing.

**Comment by ulankford** [comment] 2018-10-03 08:05
I am seeing the same behaviour as above.

e.g.
`PS C:\> Get-DrsVMGroup
Unable to find type [DRSRule.VMGroup].
At C:\Program Files\WindowsPowerShell\Modules\DRSRule\1.2.1\DRSRule.psm1:55 char:15
+   [OutputType([DRSRule.VMGroup],[VMware.Vim.ClusterVmGroup])]
+               ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DRSRule.VMGroup:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound`

I installed the module using 
`Find-Module DRSRule | Install-Module`

Appears to be installed
`PS C:\> get-module -name DRSrule -listavailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.1      DRSRule                             {Get-DrsVMGroup, Get-DrsVMHostGroup, Get-DrsVMToVMHostRule...

`

**Comment by ulankford** [comment] 2018-10-03 08:36
Hmmm, even a manual installation gives the same error as shown in the initial OP.

> PowerCLI C:\> get-drsvmgroup
Unable to find type [DRSRule.VMGroup].
At C:\Program Files (x86)\VMware\Infrastructure\PowerCLI\Modules\DRSRule\DRSRule.psm1:55 char:15
+   [OutputType([DRSRule.VMGroup],[VMware.Vim.ClusterVmGroup])]
+               ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (DRSRule.VMGroup:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

>

**Comment by Poolshark314** [comment] 2018-10-24 18:36
I am having the same issue, even after modifying the top of my C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI\Modules\DRSRule\DRSRule.init.ps1 file with:

$pcliDll = "${env:\ProgramFiles(x86)}\VMware\Infrastructure\PowerCLI\Modules\VMware.VimAutomation.Core\VMware.Vim.dll”

My PowerCLI build is 11.0.0 build 10380590 and using DRSRule 1.2.1

**Comment by cc4in** [comment] 2018-10-25 09:29
I didn't solve it, but just went on using the features, vmware powercli gives us with 6.5 by itself. 
Not the best way, i know, but it's enough for my environment and my requirements.

Nonetheless i'd be interested if someone finds a solution for this...

**Comment by sand5turm** [comment] 2018-10-25 14:46
I found a workaround. I modified the line 23 in the file "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DRSRule\DRSRule.init.ps1" with the correct path to the VMware.Vim.dll:
_$strVMwareVimDllFilespec = "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\VMware.Vim\net45\VMware.Vim.dll"_

I haven't found any problems with this modification in my existing scripts until now.

**Comment by Poolshark314** [comment] 2018-10-25 15:42
Thanks sand5turm.  I was able to do what you did but my DRSRule.init.ps1 file was located at: C:\Program Files\Windows PowerShell\Modules\DRSRule\1.2.1\DRSRule.init.ps1

and my VMware.Vim.dll was located at: C:\Program Files\WindowsPowerShell\Modules\VMware.Vim\6.7.0.10334489\net45\VMware.Vim.dll

I also modified C:\Program Files\VMware\Infrastructure\vSphere PowerCLI\Modules\DRSRule\DRSRule.init.ps1 and modified $pcliDll to be "${env:\ProgramFiles(x86)}\VMware\Infrastructure\PowerCLI\Modules\VMware.VimAutomation.Core\VMware.Vim.dll"

Now I no longer get an error while running Get-DRSVMGroup

**Comment by mtboren** [comment] 2018-10-26 01:00
Greets-
Thanks for the details on what things are / are not working for you guys.  I have found and coded around one of the bugs, now addressed in commit 0337916 (the `Metadata file ...\net45\VMware.Vim.dll' could not be found` issue).

I'm still looking into the other bug (`Unable to find type [DRSRule.VMGroup]`).

**Comment by Poolshark314** [comment] 2018-10-26 13:20
Matt,

The post I wrote yesterday was for addressing the (Unable to find type [DRSRule.VMGroup]) bug.  Hopefully that helps

**Comment by mtboren** [comment] 2018-10-27 13:56
Got it, @Poolshark314 -- thanks

**Comment by gerguk** [comment] 2018-10-30 15:38
I'm having problems with Export-DRSRule. I get the following error:

```
PS C:\Users\My.Name> Get-Cluster "My Cluster" | Export-DrsRule -Name "DRSRule1" -Path "C:\Users\My.Name\Documents\DRS Rules\myrules.json"
Unable to find type [DRSRule.VMToVMRule].
At C:\Program Files\PowerShell\Modules\DRSRule\1.2.1\DRSRule.psm1:271 char:15
+   [OutputType([DRSRule.VMToVMRule],[VMware.Vim.ClusterAffinityRuleSpe ...
+               ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (DRSRule.VMToVMRule:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
```

I'm using PowerShell Core version 6.1.0 
```
PS C:\Users\My.Name> Get-Module | where name -Like VMware* | Select Version,Name

Version        Name
6.7.0.9288211  VMware.Vim
10.1.0.8377811 VMware.VimAutomation.Cis.Core
10.1.0.8342134 VMware.VimAutomation.Common
10.1.0.8344055 VMware.VimAutomation.Core
10.1.0.8342078 VMware.VimAutomation.Sdk
10.1.0.8344219 VMware.VimAutomation.Vds
```

And version 1.2.1 of DRSRule

Thanks in advance,
Greg

**Comment by mtboren** [comment] 2018-11-16 01:14
Working on wrapping up a v2.0 release.  Such a release removes the ultimate cause of the problems in this issue (#17) -- instead of trying to handle the endless places in which some reference DLL might reside, the module in v2.0 leverages native PowerShell Classes, doing away with the DLL reference that caused more than a few problems in the 1.x line.

**Closed** 2018-11-16 01:29 UTC
Labels: bug, question

**Comment by Poolshark314** [comment] 2019-06-20 14:57
I just updated my DRSRule to version 2.0 and now I am getting this error again. It is stating that the issue is in: C:\Program Files\WindowsPowerShell\Modules\DRSRule\2.0.0\DRSRule.psm1 on line 91 char 11 which is the New-Object declaration of type DRSRule_VMGroup.

The fix I mentioned in earlier comments seems to be longer applicable because I don't see those variables in the files any longer. Do you have any suggestions? I also just updated to PowerCli 11.2

**Comment by gillx0101** [comment] 2019-10-01 11:25
Can someone help! I'm able to use the export-drsrule successfully, but get errors when importing the txt file with the following;

Get-DrsRuleObject : Cannot validate argument on parameter 'Object'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\DRSRule\2.0.0\DRSRule.psm1:1572 char:38
+ ... _filtered | Get-DrsRuleObject -Type 'ClusterAffinityRuleSpec|ClusterA ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-DrsRuleObject], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-DrsRuleObject

I am using Powercli VMware PowerCLI 11.3.0 build 13990089 and verion 2.0.0 of the DRSRule.

I am testing with vcentre 6.7, creating a test VM/Host group, exporting out then deleting from vmware and trying to import back in from the export file. Any pointers would be appreciated.

**Comment by mtboren** [comment] 2019-10-01 21:16
Hello, @gillx0101 -

I opened a new GitHub Issue for the issue you reported (this current issue 17 is closed).  Let us converse at [Issue #23](https://github.com/PowerCLIGoodies/DRSRule/issues/23)
Matt
